var blueCushionSprite = new Image();
		blueCushionSprite.src = "sprites/overworld/blueCushion.png"
		blueCushionSprite.height = 16
		blueCushionSprite.width = 16
var blueRug1Sprite = new Image();
		blueRug1Sprite.src = "sprites/overworld/blueRug1.png"
		blueRug1Sprite.height = 16
		blueRug1Sprite.width = 16
var blueRug2Sprite = new Image();
		blueRug2Sprite.src = "sprites/overworld/blueRug2.png"
		blueRug2Sprite.height = 16
		blueRug2Sprite.width = 16
var blueRug3Sprite = new Image();
		blueRug3Sprite.src = "sprites/overworld/blueRug3.png"
		blueRug3Sprite.height = 16
		blueRug3Sprite.width = 16
var blueRug4Sprite = new Image();
		blueRug4Sprite.src = "sprites/overworld/blueRug4.png"
		blueRug4Sprite.height = 16
		blueRug4Sprite.width = 16
var blueRug5Sprite = new Image();
		blueRug5Sprite.src = "sprites/overworld/blueRug5.png"
		blueRug5Sprite.height = 16
		blueRug5Sprite.width = 16
var blueRug6Sprite = new Image();
		blueRug6Sprite.src = "sprites/overworld/blueRug6.png"
		blueRug6Sprite.height = 16
		blueRug6Sprite.width = 16
var blueRug7Sprite = new Image();
		blueRug7Sprite.src = "sprites/overworld/blueRug7.png"
		blueRug7Sprite.height = 16
		blueRug7Sprite.width = 16
var blueRug8Sprite = new Image();
		blueRug8Sprite.src = "sprites/overworld/blueRug8.png"
		blueRug8Sprite.height = 16
		blueRug8Sprite.width = 16
var blueRug9Sprite = new Image();
		blueRug9Sprite.src = "sprites/overworld/blueRug9.png"
		blueRug9Sprite.height = 16
		blueRug9Sprite.width = 16
var blueStoolSprite = new Image();
		blueStoolSprite.src = "sprites/overworld/blueStool.png"
		blueStoolSprite.height = 16
		blueStoolSprite.width = 16
var bushSprite = new Image();
		bushSprite.src = "sprites/overworld/bush.png"
		bushSprite.height = 16
		bushSprite.width = 16
var curtain1Sprite = new Image();
		curtain1Sprite.src = "sprites/overworld/curtain1.png"
		curtain1Sprite.height = 16
		curtain1Sprite.width = 16
var curtain2Sprite = new Image();
		curtain2Sprite.src = "sprites/overworld/curtain2.png"
		curtain2Sprite.height = 16
		curtain2Sprite.width = 16
var curtain3Sprite = new Image();
		curtain3Sprite.src = "sprites/overworld/curtain3.png"
		curtain3Sprite.height = 16
		curtain3Sprite.width = 16
var curtain4Sprite = new Image();
		curtain4Sprite.src = "sprites/overworld/curtain4.png"
		curtain4Sprite.height = 16
		curtain4Sprite.width = 16
var flowerSprite = new Image();
		flowerSprite.src = "sprites/overworld/flower.png"
		flowerSprite.height = 16
		flowerSprite.width = 16
var friendSprite = new Image();
		friendSprite.src = "sprites/overworld/friend.png"
		friendSprite.height = 16
		friendSprite.width = 16
var grassSprite = new Image();
		grassSprite.src = "sprites/overworld/grass.png"
		grassSprite.height = 16
		grassSprite.width = 16
var house00Sprite = new Image();
		house00Sprite.src = "sprites/overworld/house00.png"
		house00Sprite.height = 16
		house00Sprite.width = 16
var house01Sprite = new Image();
		house01Sprite.src = "sprites/overworld/house01.png"
		house01Sprite.height = 16
		house01Sprite.width = 16
var house010Sprite = new Image();
		house010Sprite.src = "sprites/overworld/house010.png"
		house010Sprite.height = 16
		house010Sprite.width = 16
var house011Sprite = new Image();
		house011Sprite.src = "sprites/overworld/house011.png"
		house011Sprite.height = 16
		house011Sprite.width = 16
var house012Sprite = new Image();
		house012Sprite.src = "sprites/overworld/house012.png"
		house012Sprite.height = 16
		house012Sprite.width = 16
var house013Sprite = new Image();
		house013Sprite.src = "sprites/overworld/house013.png"
		house013Sprite.height = 16
		house013Sprite.width = 16
var house014Sprite = new Image();
		house014Sprite.src = "sprites/overworld/house014.png"
		house014Sprite.height = 16
		house014Sprite.width = 16
var house015Sprite = new Image();
		house015Sprite.src = "sprites/overworld/house015.png"
		house015Sprite.height = 16
		house015Sprite.width = 16
var house016Sprite = new Image();
		house016Sprite.src = "sprites/overworld/house016.png"
		house016Sprite.height = 16
		house016Sprite.width = 16
var house017Sprite = new Image();
		house017Sprite.src = "sprites/overworld/house017.png"
		house017Sprite.height = 16
		house017Sprite.width = 16
var house018Sprite = new Image();
		house018Sprite.src = "sprites/overworld/house018.png"
		house018Sprite.height = 16
		house018Sprite.width = 16
var house019Sprite = new Image();
		house019Sprite.src = "sprites/overworld/house019.png"
		house019Sprite.height = 16
		house019Sprite.width = 16
var house02Sprite = new Image();
		house02Sprite.src = "sprites/overworld/house02.png"
		house02Sprite.height = 16
		house02Sprite.width = 16
var house020Sprite = new Image();
		house020Sprite.src = "sprites/overworld/house020.png"
		house020Sprite.height = 16
		house020Sprite.width = 16
var house021Sprite = new Image();
		house021Sprite.src = "sprites/overworld/house021.png"
		house021Sprite.height = 16
		house021Sprite.width = 16
var house022Sprite = new Image();
		house022Sprite.src = "sprites/overworld/house022.png"
		house022Sprite.height = 16
		house022Sprite.width = 16
var house023Sprite = new Image();
		house023Sprite.src = "sprites/overworld/house023.png"
		house023Sprite.height = 16
		house023Sprite.width = 16
var house024Sprite = new Image();
		house024Sprite.src = "sprites/overworld/house024.png"
		house024Sprite.height = 16
		house024Sprite.width = 16
var house03Sprite = new Image();
		house03Sprite.src = "sprites/overworld/house03.png"
		house03Sprite.height = 16
		house03Sprite.width = 16
var house04Sprite = new Image();
		house04Sprite.src = "sprites/overworld/house04.png"
		house04Sprite.height = 16
		house04Sprite.width = 16
var house05Sprite = new Image();
		house05Sprite.src = "sprites/overworld/house05.png"
		house05Sprite.height = 16
		house05Sprite.width = 16
var house06Sprite = new Image();
		house06Sprite.src = "sprites/overworld/house06.png"
		house06Sprite.height = 16
		house06Sprite.width = 16
var house07Sprite = new Image();
		house07Sprite.src = "sprites/overworld/house07.png"
		house07Sprite.height = 16
		house07Sprite.width = 16
var house08Sprite = new Image();
		house08Sprite.src = "sprites/overworld/house08.png"
		house08Sprite.height = 16
		house08Sprite.width = 16
var house09Sprite = new Image();
		house09Sprite.src = "sprites/overworld/house09.png"
		house09Sprite.height = 16
		house09Sprite.width = 16
var lampBottomLeftSprite = new Image();
		lampBottomLeftSprite.src = "sprites/overworld/lampBottomLeft.png"
		lampBottomLeftSprite.height = 16
		lampBottomLeftSprite.width = 16
var lampBottomRightSprite = new Image();
		lampBottomRightSprite.src = "sprites/overworld/lampBottomRight.png"
		lampBottomRightSprite.height = 16
		lampBottomRightSprite.width = 16
var lampMiddleLeftSprite = new Image();
		lampMiddleLeftSprite.src = "sprites/overworld/lampMiddleLeft.png"
		lampMiddleLeftSprite.height = 16
		lampMiddleLeftSprite.width = 16
var lampMiddleRightSprite = new Image();
		lampMiddleRightSprite.src = "sprites/overworld/lampMiddleRight.png"
		lampMiddleRightSprite.height = 16
		lampMiddleRightSprite.width = 16
var lampTopLeftSprite = new Image();
		lampTopLeftSprite.src = "sprites/overworld/lampTopLeft.png"
		lampTopLeftSprite.height = 16
		lampTopLeftSprite.width = 16
var lampTopRightSprite = new Image();
		lampTopRightSprite.src = "sprites/overworld/lampTopRight.png"
		lampTopRightSprite.height = 16
		lampTopRightSprite.width = 16
var longGrassSprite = new Image();
		longGrassSprite.src = "sprites/overworld/longGrass.png"
		longGrassSprite.height = 16
		longGrassSprite.width = 16
var longGrass2Sprite = new Image();
		longGrass2Sprite.src = "sprites/overworld/longGrass2.png"
		longGrass2Sprite.height = 16
		longGrass2Sprite.width = 16
var longGrass3Sprite = new Image();
		longGrass3Sprite.src = "sprites/overworld/longGrass3.png"
		longGrass3Sprite.height = 16
		longGrass3Sprite.width = 16
var path0BottomLeftSprite = new Image();
		path0BottomLeftSprite.src = "sprites/overworld/path0BottomLeft.png"
		path0BottomLeftSprite.height = 16
		path0BottomLeftSprite.width = 16
var path0BottomMiddleSprite = new Image();
		path0BottomMiddleSprite.src = "sprites/overworld/path0BottomMiddle.png"
		path0BottomMiddleSprite.height = 16
		path0BottomMiddleSprite.width = 16
var path0BottomRightSprite = new Image();
		path0BottomRightSprite.src = "sprites/overworld/path0BottomRight.png"
		path0BottomRightSprite.height = 16
		path0BottomRightSprite.width = 16
var path0MiddleSprite = new Image();
		path0MiddleSprite.src = "sprites/overworld/path0Middle.png"
		path0MiddleSprite.height = 16
		path0MiddleSprite.width = 16
var path0MiddleLeftSprite = new Image();
		path0MiddleLeftSprite.src = "sprites/overworld/path0MiddleLeft.png"
		path0MiddleLeftSprite.height = 16
		path0MiddleLeftSprite.width = 16
var path0MiddleRightSprite = new Image();
		path0MiddleRightSprite.src = "sprites/overworld/path0MiddleRight.png"
		path0MiddleRightSprite.height = 16
		path0MiddleRightSprite.width = 16
var path0TopLeftSprite = new Image();
		path0TopLeftSprite.src = "sprites/overworld/path0TopLeft.png"
		path0TopLeftSprite.height = 16
		path0TopLeftSprite.width = 16
var path0TopMiddleSprite = new Image();
		path0TopMiddleSprite.src = "sprites/overworld/path0TopMiddle.png"
		path0TopMiddleSprite.height = 16
		path0TopMiddleSprite.width = 16
var path0TopRightSprite = new Image();
		path0TopRightSprite.src = "sprites/overworld/path0TopRight.png"
		path0TopRightSprite.height = 16
		path0TopRightSprite.width = 16
var playerSprite = new Image();
		playerSprite.src = "sprites/overworld/player.png"
		playerSprite.height = 16
		playerSprite.width = 16
var redRug1Sprite = new Image();
		redRug1Sprite.src = "sprites/overworld/redRug1.png"
		redRug1Sprite.height = 16
		redRug1Sprite.width = 16
var redRug2Sprite = new Image();
		redRug2Sprite.src = "sprites/overworld/redRug2.png"
		redRug2Sprite.height = 16
		redRug2Sprite.width = 16
var ThumbSprite = new Image();
		ThumbSprite.src = "sprites/overworld/Thumbs.db"
		ThumbSprite.height = 16
		ThumbSprite.width = 16
var treeBottomSprite = new Image();
		treeBottomSprite.src = "sprites/overworld/treeBottom.png"
		treeBottomSprite.height = 16
		treeBottomSprite.width = 16
var treeMiddleSprite = new Image();
		treeMiddleSprite.src = "sprites/overworld/treeMiddle.png"
		treeMiddleSprite.height = 16
		treeMiddleSprite.width = 16
var treeTopSprite = new Image();
		treeTopSprite.src = "sprites/overworld/treeTop.png"
		treeTopSprite.height = 16
		treeTopSprite.width = 16
var tv1Sprite = new Image();
		tv1Sprite.src = "sprites/overworld/tv1.png"
		tv1Sprite.height = 16
		tv1Sprite.width = 16
var tv2Sprite = new Image();
		tv2Sprite.src = "sprites/overworld/tv2.png"
		tv2Sprite.height = 16
		tv2Sprite.width = 16
var tv3Sprite = new Image();
		tv3Sprite.src = "sprites/overworld/tv3.png"
		tv3Sprite.height = 16
		tv3Sprite.width = 16
var tv4Sprite = new Image();
		tv4Sprite.src = "sprites/overworld/tv4.png"
		tv4Sprite.height = 16
		tv4Sprite.width = 16
var waterSprite = new Image();
		waterSprite.src = "sprites/overworld/water.png"
		waterSprite.height = 16
		waterSprite.width = 16
var waterBottomLeftSprite = new Image();
		waterBottomLeftSprite.src = "sprites/overworld/waterBottomLeft.png"
		waterBottomLeftSprite.height = 16
		waterBottomLeftSprite.width = 16
var waterBottomMiddleSprite = new Image();
		waterBottomMiddleSprite.src = "sprites/overworld/waterBottomMiddle.png"
		waterBottomMiddleSprite.height = 16
		waterBottomMiddleSprite.width = 16
var waterBottomRightSprite = new Image();
		waterBottomRightSprite.src = "sprites/overworld/waterBottomRight.png"
		waterBottomRightSprite.height = 16
		waterBottomRightSprite.width = 16
var waterMiddleLeftSprite = new Image();
		waterMiddleLeftSprite.src = "sprites/overworld/waterMiddleLeft.png"
		waterMiddleLeftSprite.height = 16
		waterMiddleLeftSprite.width = 16
var waterMiddleRightSprite = new Image();
		waterMiddleRightSprite.src = "sprites/overworld/waterMiddleRight.png"
		waterMiddleRightSprite.height = 16
		waterMiddleRightSprite.width = 16
var waterTopSprite = new Image();
		waterTopSprite.src = "sprites/overworld/waterTop.png"
		waterTopSprite.height = 16
		waterTopSprite.width = 16
var waterTopLeftSprite = new Image();
		waterTopLeftSprite.src = "sprites/overworld/waterTopLeft.png"
		waterTopLeftSprite.height = 16
		waterTopLeftSprite.width = 16
var waterTopRightSprite = new Image();
		waterTopRightSprite.src = "sprites/overworld/waterTopRight.png"
		waterTopRightSprite.height = 16
		waterTopRightSprite.width = 16
var woodFenceBottomLeftSprite = new Image();
		woodFenceBottomLeftSprite.src = "sprites/overworld/woodFenceBottomLeft.png"
		woodFenceBottomLeftSprite.height = 16
		woodFenceBottomLeftSprite.width = 16
var woodFenceBottomRightSprite = new Image();
		woodFenceBottomRightSprite.src = "sprites/overworld/woodFenceBottomRight.png"
		woodFenceBottomRightSprite.height = 16
		woodFenceBottomRightSprite.width = 16
var woodFenceMiddleLeftSprite = new Image();
		woodFenceMiddleLeftSprite.src = "sprites/overworld/woodFenceMiddleLeft.png"
		woodFenceMiddleLeftSprite.height = 16
		woodFenceMiddleLeftSprite.width = 16
var woodFenceMiddleRightSprite = new Image();
		woodFenceMiddleRightSprite.src = "sprites/overworld/woodFenceMiddleRight.png"
		woodFenceMiddleRightSprite.height = 16
		woodFenceMiddleRightSprite.width = 16
var woodFenceTopSprite = new Image();
		woodFenceTopSprite.src = "sprites/overworld/woodFenceTop.png"
		woodFenceTopSprite.height = 16
		woodFenceTopSprite.width = 16
var woodFenceTopLeftSprite = new Image();
		woodFenceTopLeftSprite.src = "sprites/overworld/woodFenceTopLeft.png"
		woodFenceTopLeftSprite.height = 16
		woodFenceTopLeftSprite.width = 16
var woodFenceTopRightSprite = new Image();
		woodFenceTopRightSprite.src = "sprites/overworld/woodFenceTopRight.png"
		woodFenceTopRightSprite.height = 16
		woodFenceTopRightSprite.width = 16
var woodFloorSprite = new Image();
		woodFloorSprite.src = "sprites/overworld/woodFloor.png"
		woodFloorSprite.height = 16
		woodFloorSprite.width = 16
var woodTable1Sprite = new Image();
		woodTable1Sprite.src = "sprites/overworld/woodTable1.png"
		woodTable1Sprite.height = 16
		woodTable1Sprite.width = 16
var woodTable2Sprite = new Image();
		woodTable2Sprite.src = "sprites/overworld/woodTable2.png"
		woodTable2Sprite.height = 16
		woodTable2Sprite.width = 16
var woodTable3Sprite = new Image();
		woodTable3Sprite.src = "sprites/overworld/woodTable3.png"
		woodTable3Sprite.height = 16
		woodTable3Sprite.width = 16
var woodTable4Sprite = new Image();
		woodTable4Sprite.src = "sprites/overworld/woodTable4.png"
		woodTable4Sprite.height = 16
		woodTable4Sprite.width = 16
var woodTable5Sprite = new Image();
		woodTable5Sprite.src = "sprites/overworld/woodTable5.png"
		woodTable5Sprite.height = 16
		woodTable5Sprite.width = 16
var woodTable6Sprite = new Image();
		woodTable6Sprite.src = "sprites/overworld/woodTable6.png"
		woodTable6Sprite.height = 16
		woodTable6Sprite.width = 16
var woodWallBottomLeftSprite = new Image();
		woodWallBottomLeftSprite.src = "sprites/overworld/woodWallBottomLeft.png"
		woodWallBottomLeftSprite.height = 16
		woodWallBottomLeftSprite.width = 16
var woodWallBottomMiddleSprite = new Image();
		woodWallBottomMiddleSprite.src = "sprites/overworld/woodWallBottomMiddle.png"
		woodWallBottomMiddleSprite.height = 16
		woodWallBottomMiddleSprite.width = 16
var woodWallBottomRightSprite = new Image();
		woodWallBottomRightSprite.src = "sprites/overworld/woodWallBottomRight.png"
		woodWallBottomRightSprite.height = 16
		woodWallBottomRightSprite.width = 16
var woodWallTopLeftSprite = new Image();
		woodWallTopLeftSprite.src = "sprites/overworld/woodWallTopLeft.png"
		woodWallTopLeftSprite.height = 16
		woodWallTopLeftSprite.width = 16
var woodWallTopMiddleSprite = new Image();
		woodWallTopMiddleSprite.src = "sprites/overworld/woodWallTopMiddle.png"
		woodWallTopMiddleSprite.height = 16
		woodWallTopMiddleSprite.width = 16
var woodWallTopRightSprite = new Image();
		woodWallTopRightSprite.src = "sprites/overworld/woodWallTopRight.png"
		woodWallTopRightSprite.height = 16
		woodWallTopRightSprite.width = 16
